---
apiVersion: "logging.openshift.io/v1"
kind: "Elasticsearch"
metadata:
  name: "elasticsearch"
spec:
  managementState: "Managed"
  nodeSpec:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 1Gi
  nodes:
  - nodeCount: 3
    roles:
    - client
    - data
    - master
    storage: {}
  redundancyPolicy: SingleRedundancy
  indexManagement:
    policies:
    - name: infra-policy
      pollInterval: 1m
      phases:
        hot:
          actions:
            rollover:
              maxAge:   2m
        delete:
          minAge: 5m
    mappings:
    - name:  infra
      policyRef: infra-policy
      aliases:
      - infra
      - logs.infra
